// server.port=8081 [changing local server port if need be]
# spring.devtools.livereload.enabled  = false
#spring.thymeleaf.cache=false
spring.thymeleaf.suffix: .html


#server.error.include-exception=true
#server.error.include-stacktrace=always